package com.iblock.dao;

import com.iblock.dao.po.Achievement;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AchievementDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACHIEVEMENT
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    int insert(Achievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACHIEVEMENT
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    int insertSelective(Achievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACHIEVEMENT
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    Achievement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACHIEVEMENT
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    int updateByPrimaryKeySelective(Achievement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACHIEVEMENT
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    int updateByPrimaryKey(Achievement record);

    List<Achievement> selectByUser(Long userId);

    Achievement selectByUserAndId(@Param("userId") Long userId, @Param("id") Long id);
}