package com.iblock.dao;

import com.iblock.dao.po.City;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    City selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CITY
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    int updateByPrimaryKey(City record);

    List<City> selectByName(@Param("name") String name);

    List<City> selectByIds(@Param("list") List<Integer> list);
}