package com.iblock.dao;

import com.iblock.dao.po.CommentDimension;

public interface CommentDimensionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_DIMENSION
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insert(CommentDimension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_DIMENSION
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insertSelective(CommentDimension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_DIMENSION
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    CommentDimension selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_DIMENSION
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKeySelective(CommentDimension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT_DIMENSION
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKey(CommentDimension record);
}