package com.iblock.dao;

import com.iblock.dao.po.Designer;

public interface DesignerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESIGNER
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insert(Designer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESIGNER
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insertSelective(Designer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESIGNER
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    Designer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESIGNER
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKeySelective(Designer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESIGNER
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKey(Designer record);
}