package com.iblock.dao;

import com.iblock.dao.po.DesignerSkill;

public interface DesignerSkillDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESIGNER_SKILL
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insert(DesignerSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESIGNER_SKILL
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insertSelective(DesignerSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESIGNER_SKILL
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    DesignerSkill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESIGNER_SKILL
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKeySelective(DesignerSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESIGNER_SKILL
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKey(DesignerSkill record);
}