package com.iblock.dao;

import com.iblock.dao.po.District;

import java.util.List;

public interface DistrictDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISTRICT
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    int insert(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISTRICT
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    int insertSelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISTRICT
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    District selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISTRICT
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    int updateByPrimaryKeySelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISTRICT
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    int updateByPrimaryKey(District record);

    List<District> selectByCity(int cityId);
}