package com.iblock.dao;

import com.iblock.dao.po.Industry;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IndustryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    int insert(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    int insertSelective(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    Industry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    int updateByPrimaryKeySelective(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDUSTRY
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    int updateByPrimaryKey(Industry record);

    List<Industry> selectAll();

    List<Industry> selectByIds(List<Integer> ids);

    Industry selectByName(@Param("name") String name);

    List<Industry> selectByIdStr(@Param("ids") String ids);
}