package com.iblock.dao;

import com.iblock.dao.po.JobInterest;

import java.util.List;

public interface JobInterestDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_INTEREST
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insert(JobInterest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_INTEREST
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insertSelective(JobInterest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_INTEREST
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    JobInterest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_INTEREST
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKeySelective(JobInterest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_INTEREST
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKey(JobInterest record);

    int updateByUserAndId(JobInterest record);

    JobInterest selectByUser(Long userId);

    List<JobInterest> selectAll();
}