package com.iblock.dao;

import com.iblock.dao.po.Message;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface MessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE
     *
     * @mbggenerated Mon Jun 13 14:03:12 CST 2016
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE
     *
     * @mbggenerated Mon Jun 13 14:03:12 CST 2016
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE
     *
     * @mbggenerated Mon Jun 13 14:03:12 CST 2016
     */
    Message selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE
     *
     * @mbggenerated Mon Jun 13 14:03:12 CST 2016
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESSAGE
     *
     * @mbggenerated Mon Jun 13 14:03:12 CST 2016
     */
    int updateByPrimaryKey(Message record);

    List<Message> selectByUserAndStatus(@Param("userId") long userId, @Param("status") List<Integer> status, @Param("offset")
    int offset, @Param("pageSize") int pageSize);

    int countByUserAndStatus(@Param("userId") long userId, @Param("status") List<Integer> status);

    List<Message> selectUnloadBroadcastMsg(@Param("time") Date time, @Param("role") Integer role);
}