package com.iblock.dao;

import com.iblock.dao.po.ProjectDesigner;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectDesignerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_DESIGNER
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    int insert(ProjectDesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_DESIGNER
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    int insertSelective(ProjectDesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_DESIGNER
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    ProjectDesigner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_DESIGNER
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    int updateByPrimaryKeySelective(ProjectDesigner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_DESIGNER
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    int updateByPrimaryKey(ProjectDesigner record);

    ProjectDesigner selectByProjectAndDesigner(@Param("project") Long project, @Param("designer") Long designer);

    List<ProjectDesigner> selectByProject(@Param("project") Long project);
}