package com.iblock.dao;

import com.iblock.dao.po.ProjectInterest;

public interface ProjectInterestDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_INTEREST
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insert(ProjectInterest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_INTEREST
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insertSelective(ProjectInterest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_INTEREST
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    ProjectInterest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_INTEREST
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKeySelective(ProjectInterest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_INTEREST
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKey(ProjectInterest record);
}