package com.iblock.dao;

import com.iblock.dao.po.ProjectSkill;
import com.iblock.dao.po.ProjectSkillDetail;

import java.util.List;

public interface ProjectSkillDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_SKILL
     *
     * @mbggenerated Sun Jul 17 12:02:29 CST 2016
     */
    int insert(ProjectSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_SKILL
     *
     * @mbggenerated Sun Jul 17 12:02:29 CST 2016
     */
    int insertSelective(ProjectSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_SKILL
     *
     * @mbggenerated Sun Jul 17 12:02:29 CST 2016
     */
    ProjectSkill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_SKILL
     *
     * @mbggenerated Sun Jul 17 12:02:29 CST 2016
     */
    int updateByPrimaryKeySelective(ProjectSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_SKILL
     *
     * @mbggenerated Sun Jul 17 12:02:29 CST 2016
     */
    int updateByPrimaryKey(ProjectSkill record);

    List<ProjectSkillDetail> selectByProject(Long project);

    int disable(Long project);
}