package com.iblock.dao;

import com.iblock.dao.po.ProjectRating;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectRatingDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_RATING
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    int insert(ProjectRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_RATING
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    int insertSelective(ProjectRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_RATING
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    ProjectRating selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_RATING
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    int updateByPrimaryKeySelective(ProjectRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_RATING
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    int updateByPrimaryKey(ProjectRating record);

    Double selectAVG(Long projectId);

    List<ProjectRating> selectByProjectAndUser(@Param("projectId") Long projectId, @Param("userId") Long userId);
}