package com.iblock.dao;

import com.iblock.dao.po.UserRating;

public interface UserRatingDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RATING
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    int insert(UserRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RATING
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    int insertSelective(UserRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RATING
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    UserRating selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RATING
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    int updateByPrimaryKeySelective(UserRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RATING
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    int updateByPrimaryKey(UserRating record);

    Double selectAVG(Long userId);

}