package com.iblock.dao;

import com.iblock.dao.po.UserRelation;
import org.apache.ibatis.annotations.Param;

public interface UserRelationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RELATION
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insert(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RELATION
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int insertSelective(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RELATION
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    UserRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RELATION
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKeySelective(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RELATION
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    int updateByPrimaryKey(UserRelation record);

    UserRelation selectByUsers(@Param("src") long src, @Param("target") long target);
}