package com.iblock.dao;

import com.iblock.dao.po.WorkExperience;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WorkExperienceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EXPERIENCE
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    int insert(WorkExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EXPERIENCE
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    int insertSelective(WorkExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EXPERIENCE
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    WorkExperience selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EXPERIENCE
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    int updateByPrimaryKeySelective(WorkExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EXPERIENCE
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(WorkExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EXPERIENCE
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    int updateByPrimaryKey(WorkExperience record);

    List<WorkExperience> selectByUserId(Long userId);

    int updateStatusByUserAndId(@Param("userId") Long userId, @Param("id") Long id, @Param("status") byte status);
}