package com.iblock.dao.po;

import java.util.Date;

public class Achievement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACHIEVEMENT.id
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACHIEVEMENT.desc
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACHIEVEMENT.user_id
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACHIEVEMENT.name
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACHIEVEMENT.url
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACHIEVEMENT.status
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACHIEVEMENT.add_time
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACHIEVEMENT.update_time
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACHIEVEMENT.id
     *
     * @return the value of ACHIEVEMENT.id
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACHIEVEMENT.id
     *
     * @param id the value for ACHIEVEMENT.id
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACHIEVEMENT.desc
     *
     * @return the value of ACHIEVEMENT.desc
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACHIEVEMENT.desc
     *
     * @param desc the value for ACHIEVEMENT.desc
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACHIEVEMENT.user_id
     *
     * @return the value of ACHIEVEMENT.user_id
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACHIEVEMENT.user_id
     *
     * @param userId the value for ACHIEVEMENT.user_id
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACHIEVEMENT.name
     *
     * @return the value of ACHIEVEMENT.name
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACHIEVEMENT.name
     *
     * @param name the value for ACHIEVEMENT.name
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACHIEVEMENT.url
     *
     * @return the value of ACHIEVEMENT.url
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACHIEVEMENT.url
     *
     * @param url the value for ACHIEVEMENT.url
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACHIEVEMENT.status
     *
     * @return the value of ACHIEVEMENT.status
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACHIEVEMENT.status
     *
     * @param status the value for ACHIEVEMENT.status
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACHIEVEMENT.add_time
     *
     * @return the value of ACHIEVEMENT.add_time
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACHIEVEMENT.add_time
     *
     * @param addTime the value for ACHIEVEMENT.add_time
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACHIEVEMENT.update_time
     *
     * @return the value of ACHIEVEMENT.update_time
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACHIEVEMENT.update_time
     *
     * @param updateTime the value for ACHIEVEMENT.update_time
     *
     * @mbggenerated Fri Jul 15 13:02:19 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}