package com.iblock.dao.po;

import java.util.Date;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.id
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.city_id
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.city_name
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.status
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.add_time
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CITY.update_time
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.id
     *
     * @return the value of CITY.id
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.id
     *
     * @param id the value for CITY.id
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.city_id
     *
     * @return the value of CITY.city_id
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.city_id
     *
     * @param cityId the value for CITY.city_id
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.city_name
     *
     * @return the value of CITY.city_name
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.city_name
     *
     * @param cityName the value for CITY.city_name
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.status
     *
     * @return the value of CITY.status
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.status
     *
     * @param status the value for CITY.status
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.add_time
     *
     * @return the value of CITY.add_time
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.add_time
     *
     * @param addTime the value for CITY.add_time
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITY.update_time
     *
     * @return the value of CITY.update_time
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITY.update_time
     *
     * @param updateTime the value for CITY.update_time
     *
     * @mbggenerated Fri Jul 01 14:26:20 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}