package com.iblock.dao.po;

import java.util.Date;

public class CommonExperience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_EXPERIENCE.id
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_EXPERIENCE.user_id
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_EXPERIENCE.friend_id
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    private Long friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_EXPERIENCE.status
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_EXPERIENCE.start_date
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_EXPERIENCE.end_date
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_EXPERIENCE.add_time
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_EXPERIENCE.update_time
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_EXPERIENCE.desc
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_EXPERIENCE.id
     *
     * @return the value of COMMON_EXPERIENCE.id
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_EXPERIENCE.id
     *
     * @param id the value for COMMON_EXPERIENCE.id
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_EXPERIENCE.user_id
     *
     * @return the value of COMMON_EXPERIENCE.user_id
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_EXPERIENCE.user_id
     *
     * @param userId the value for COMMON_EXPERIENCE.user_id
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_EXPERIENCE.friend_id
     *
     * @return the value of COMMON_EXPERIENCE.friend_id
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public Long getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_EXPERIENCE.friend_id
     *
     * @param friendId the value for COMMON_EXPERIENCE.friend_id
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_EXPERIENCE.status
     *
     * @return the value of COMMON_EXPERIENCE.status
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_EXPERIENCE.status
     *
     * @param status the value for COMMON_EXPERIENCE.status
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_EXPERIENCE.start_date
     *
     * @return the value of COMMON_EXPERIENCE.start_date
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_EXPERIENCE.start_date
     *
     * @param startDate the value for COMMON_EXPERIENCE.start_date
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_EXPERIENCE.end_date
     *
     * @return the value of COMMON_EXPERIENCE.end_date
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_EXPERIENCE.end_date
     *
     * @param endDate the value for COMMON_EXPERIENCE.end_date
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_EXPERIENCE.add_time
     *
     * @return the value of COMMON_EXPERIENCE.add_time
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_EXPERIENCE.add_time
     *
     * @param addTime the value for COMMON_EXPERIENCE.add_time
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_EXPERIENCE.update_time
     *
     * @return the value of COMMON_EXPERIENCE.update_time
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_EXPERIENCE.update_time
     *
     * @param updateTime the value for COMMON_EXPERIENCE.update_time
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_EXPERIENCE.desc
     *
     * @return the value of COMMON_EXPERIENCE.desc
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_EXPERIENCE.desc
     *
     * @param desc the value for COMMON_EXPERIENCE.desc
     *
     * @mbggenerated Sun Feb 14 20:53:38 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}