package com.iblock.dao.po;

import java.util.Date;

public class DesignerSkill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER_SKILL.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER_SKILL.designer_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long designerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER_SKILL.skill_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Integer skillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER_SKILL.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER_SKILL.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER_SKILL.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER_SKILL.id
     *
     * @return the value of DESIGNER_SKILL.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER_SKILL.id
     *
     * @param id the value for DESIGNER_SKILL.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER_SKILL.designer_id
     *
     * @return the value of DESIGNER_SKILL.designer_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER_SKILL.designer_id
     *
     * @param designerId the value for DESIGNER_SKILL.designer_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setDesignerId(Long designerId) {
        this.designerId = designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER_SKILL.skill_id
     *
     * @return the value of DESIGNER_SKILL.skill_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Integer getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER_SKILL.skill_id
     *
     * @param skillId the value for DESIGNER_SKILL.skill_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER_SKILL.status
     *
     * @return the value of DESIGNER_SKILL.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER_SKILL.status
     *
     * @param status the value for DESIGNER_SKILL.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER_SKILL.add_time
     *
     * @return the value of DESIGNER_SKILL.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER_SKILL.add_time
     *
     * @param addTime the value for DESIGNER_SKILL.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER_SKILL.update_time
     *
     * @return the value of DESIGNER_SKILL.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER_SKILL.update_time
     *
     * @param updateTime the value for DESIGNER_SKILL.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}