package com.iblock.dao.po;

import java.util.Date;

public class Designer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER.location
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER.city
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER.address
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER.education
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Byte education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER.visible
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Boolean visible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DESIGNER.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER.id
     *
     * @return the value of DESIGNER.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER.id
     *
     * @param id the value for DESIGNER.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER.user_id
     *
     * @return the value of DESIGNER.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER.user_id
     *
     * @param userId the value for DESIGNER.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER.location
     *
     * @return the value of DESIGNER.location
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER.location
     *
     * @param location the value for DESIGNER.location
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER.city
     *
     * @return the value of DESIGNER.city
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER.city
     *
     * @param city the value for DESIGNER.city
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER.address
     *
     * @return the value of DESIGNER.address
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER.address
     *
     * @param address the value for DESIGNER.address
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER.education
     *
     * @return the value of DESIGNER.education
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Byte getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER.education
     *
     * @param education the value for DESIGNER.education
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setEducation(Byte education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER.visible
     *
     * @return the value of DESIGNER.visible
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Boolean getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER.visible
     *
     * @param visible the value for DESIGNER.visible
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER.add_time
     *
     * @return the value of DESIGNER.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER.add_time
     *
     * @param addTime the value for DESIGNER.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DESIGNER.update_time
     *
     * @return the value of DESIGNER.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DESIGNER.update_time
     *
     * @param updateTime the value for DESIGNER.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}