package com.iblock.dao.po;

import java.math.BigDecimal;
import java.util.Date;

public class District {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISTRICT.id
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISTRICT.city_id
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISTRICT.name
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISTRICT.lantitude
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    private BigDecimal lantitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISTRICT.longitude
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISTRICT.status
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISTRICT.add_time
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISTRICT.update_time
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISTRICT.id
     *
     * @return the value of DISTRICT.id
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISTRICT.id
     *
     * @param id the value for DISTRICT.id
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISTRICT.city_id
     *
     * @return the value of DISTRICT.city_id
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISTRICT.city_id
     *
     * @param cityId the value for DISTRICT.city_id
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISTRICT.name
     *
     * @return the value of DISTRICT.name
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISTRICT.name
     *
     * @param name the value for DISTRICT.name
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISTRICT.lantitude
     *
     * @return the value of DISTRICT.lantitude
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public BigDecimal getLantitude() {
        return lantitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISTRICT.lantitude
     *
     * @param lantitude the value for DISTRICT.lantitude
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public void setLantitude(BigDecimal lantitude) {
        this.lantitude = lantitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISTRICT.longitude
     *
     * @return the value of DISTRICT.longitude
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISTRICT.longitude
     *
     * @param longitude the value for DISTRICT.longitude
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISTRICT.status
     *
     * @return the value of DISTRICT.status
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISTRICT.status
     *
     * @param status the value for DISTRICT.status
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISTRICT.add_time
     *
     * @return the value of DISTRICT.add_time
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISTRICT.add_time
     *
     * @param addTime the value for DISTRICT.add_time
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISTRICT.update_time
     *
     * @return the value of DISTRICT.update_time
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISTRICT.update_time
     *
     * @param updateTime the value for DISTRICT.update_time
     *
     * @mbggenerated Wed Feb 03 16:10:47 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}