package com.iblock.dao.po;

import java.util.Date;

public class Industry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDUSTRY.id
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDUSTRY.name
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDUSTRY.status
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDUSTRY.add_time
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDUSTRY.update_time
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDUSTRY.id
     *
     * @return the value of INDUSTRY.id
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDUSTRY.id
     *
     * @param id the value for INDUSTRY.id
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDUSTRY.name
     *
     * @return the value of INDUSTRY.name
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDUSTRY.name
     *
     * @param name the value for INDUSTRY.name
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDUSTRY.status
     *
     * @return the value of INDUSTRY.status
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDUSTRY.status
     *
     * @param status the value for INDUSTRY.status
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDUSTRY.add_time
     *
     * @return the value of INDUSTRY.add_time
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDUSTRY.add_time
     *
     * @param addTime the value for INDUSTRY.add_time
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDUSTRY.update_time
     *
     * @return the value of INDUSTRY.update_time
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDUSTRY.update_time
     *
     * @param updateTime the value for INDUSTRY.update_time
     *
     * @mbggenerated Mon Jun 27 13:33:12 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}