package com.iblock.dao.po;

import java.util.Date;

public class JobInterest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_INTEREST.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_INTEREST.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_INTEREST.start_pay
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Integer startPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_INTEREST.end_pay
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Integer endPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_INTEREST.resident
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Boolean resident;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_INTEREST.job_type
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Integer jobType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_INTEREST.city_list
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String cityList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_INTEREST.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_INTEREST.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_INTEREST.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_INTEREST.id
     *
     * @return the value of JOB_INTEREST.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_INTEREST.id
     *
     * @param id the value for JOB_INTEREST.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_INTEREST.user_id
     *
     * @return the value of JOB_INTEREST.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_INTEREST.user_id
     *
     * @param userId the value for JOB_INTEREST.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_INTEREST.start_pay
     *
     * @return the value of JOB_INTEREST.start_pay
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Integer getStartPay() {
        return startPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_INTEREST.start_pay
     *
     * @param startPay the value for JOB_INTEREST.start_pay
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStartPay(Integer startPay) {
        this.startPay = startPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_INTEREST.end_pay
     *
     * @return the value of JOB_INTEREST.end_pay
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Integer getEndPay() {
        return endPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_INTEREST.end_pay
     *
     * @param endPay the value for JOB_INTEREST.end_pay
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setEndPay(Integer endPay) {
        this.endPay = endPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_INTEREST.resident
     *
     * @return the value of JOB_INTEREST.resident
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Boolean getResident() {
        return resident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_INTEREST.resident
     *
     * @param resident the value for JOB_INTEREST.resident
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setResident(Boolean resident) {
        this.resident = resident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_INTEREST.job_type
     *
     * @return the value of JOB_INTEREST.job_type
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Integer getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_INTEREST.job_type
     *
     * @param jobType the value for JOB_INTEREST.job_type
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setJobType(Integer jobType) {
        this.jobType = jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_INTEREST.city_list
     *
     * @return the value of JOB_INTEREST.city_list
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getCityList() {
        return cityList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_INTEREST.city_list
     *
     * @param cityList the value for JOB_INTEREST.city_list
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setCityList(String cityList) {
        this.cityList = cityList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_INTEREST.status
     *
     * @return the value of JOB_INTEREST.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_INTEREST.status
     *
     * @param status the value for JOB_INTEREST.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_INTEREST.add_time
     *
     * @return the value of JOB_INTEREST.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_INTEREST.add_time
     *
     * @param addTime the value for JOB_INTEREST.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_INTEREST.update_time
     *
     * @return the value of JOB_INTEREST.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_INTEREST.update_time
     *
     * @param updateTime the value for JOB_INTEREST.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}