package com.iblock.dao.po;

import java.util.Date;

public class Manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER.company_name
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER.city
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER.address
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER.desc
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAGER.id
     *
     * @return the value of MANAGER.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAGER.id
     *
     * @param id the value for MANAGER.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAGER.user_id
     *
     * @return the value of MANAGER.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAGER.user_id
     *
     * @param userId the value for MANAGER.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAGER.company_name
     *
     * @return the value of MANAGER.company_name
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAGER.company_name
     *
     * @param companyName the value for MANAGER.company_name
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAGER.city
     *
     * @return the value of MANAGER.city
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAGER.city
     *
     * @param city the value for MANAGER.city
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAGER.address
     *
     * @return the value of MANAGER.address
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAGER.address
     *
     * @param address the value for MANAGER.address
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAGER.status
     *
     * @return the value of MANAGER.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAGER.status
     *
     * @param status the value for MANAGER.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAGER.add_time
     *
     * @return the value of MANAGER.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAGER.add_time
     *
     * @param addTime the value for MANAGER.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAGER.update_time
     *
     * @return the value of MANAGER.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAGER.update_time
     *
     * @param updateTime the value for MANAGER.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MANAGER.desc
     *
     * @return the value of MANAGER.desc
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MANAGER.desc
     *
     * @param desc the value for MANAGER.desc
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}