package com.iblock.dao.po;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE.action
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Integer action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE.detail
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE.source_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE.target_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MESSAGE.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE.id
     *
     * @return the value of MESSAGE.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE.id
     *
     * @param id the value for MESSAGE.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE.action
     *
     * @return the value of MESSAGE.action
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Integer getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE.action
     *
     * @param action the value for MESSAGE.action
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAction(Integer action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE.detail
     *
     * @return the value of MESSAGE.detail
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE.detail
     *
     * @param detail the value for MESSAGE.detail
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE.source_id
     *
     * @return the value of MESSAGE.source_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE.source_id
     *
     * @param sourceId the value for MESSAGE.source_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE.target_id
     *
     * @return the value of MESSAGE.target_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE.target_id
     *
     * @param targetId the value for MESSAGE.target_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE.status
     *
     * @return the value of MESSAGE.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE.status
     *
     * @param status the value for MESSAGE.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE.add_time
     *
     * @return the value of MESSAGE.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE.add_time
     *
     * @param addTime the value for MESSAGE.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MESSAGE.update_time
     *
     * @return the value of MESSAGE.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MESSAGE.update_time
     *
     * @param updateTime the value for MESSAGE.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}