package com.iblock.dao.po;

import java.util.Date;

public class ProjectInterest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_INTEREST.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_INTEREST.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_INTEREST.project_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_INTEREST.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_INTEREST.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_INTEREST.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_INTEREST.id
     *
     * @return the value of PROJECT_INTEREST.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_INTEREST.id
     *
     * @param id the value for PROJECT_INTEREST.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_INTEREST.user_id
     *
     * @return the value of PROJECT_INTEREST.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_INTEREST.user_id
     *
     * @param userId the value for PROJECT_INTEREST.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_INTEREST.project_id
     *
     * @return the value of PROJECT_INTEREST.project_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_INTEREST.project_id
     *
     * @param projectId the value for PROJECT_INTEREST.project_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_INTEREST.status
     *
     * @return the value of PROJECT_INTEREST.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_INTEREST.status
     *
     * @param status the value for PROJECT_INTEREST.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_INTEREST.add_time
     *
     * @return the value of PROJECT_INTEREST.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_INTEREST.add_time
     *
     * @param addTime the value for PROJECT_INTEREST.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_INTEREST.update_time
     *
     * @return the value of PROJECT_INTEREST.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_INTEREST.update_time
     *
     * @param updateTime the value for PROJECT_INTEREST.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}