package com.iblock.dao.po;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.name
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.manager_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.agent_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.resident
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Boolean resident;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.city
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.address
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.achievement_visable
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Boolean achievementVisable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.desc
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.id
     *
     * @return the value of PROJECT.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.id
     *
     * @param id the value for PROJECT.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.name
     *
     * @return the value of PROJECT.name
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.name
     *
     * @param name the value for PROJECT.name
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.manager_id
     *
     * @return the value of PROJECT.manager_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.manager_id
     *
     * @param managerId the value for PROJECT.manager_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.agent_id
     *
     * @return the value of PROJECT.agent_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.agent_id
     *
     * @param agentId the value for PROJECT.agent_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.status
     *
     * @return the value of PROJECT.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.status
     *
     * @param status the value for PROJECT.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.resident
     *
     * @return the value of PROJECT.resident
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Boolean getResident() {
        return resident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.resident
     *
     * @param resident the value for PROJECT.resident
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setResident(Boolean resident) {
        this.resident = resident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.city
     *
     * @return the value of PROJECT.city
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.city
     *
     * @param city the value for PROJECT.city
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.address
     *
     * @return the value of PROJECT.address
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.address
     *
     * @param address the value for PROJECT.address
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.achievement_visable
     *
     * @return the value of PROJECT.achievement_visable
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Boolean getAchievementVisable() {
        return achievementVisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.achievement_visable
     *
     * @param achievementVisable the value for PROJECT.achievement_visable
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAchievementVisable(Boolean achievementVisable) {
        this.achievementVisable = achievementVisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.add_time
     *
     * @return the value of PROJECT.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.add_time
     *
     * @param addTime the value for PROJECT.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.update_time
     *
     * @return the value of PROJECT.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.update_time
     *
     * @param updateTime the value for PROJECT.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.desc
     *
     * @return the value of PROJECT.desc
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.desc
     *
     * @param desc the value for PROJECT.desc
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}