package com.iblock.dao.po;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.id
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.industry
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Integer industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.name
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.manager_id
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Long managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.agent_id
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Long agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.status
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.resident
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Boolean resident;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.city
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.min_pay
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Integer minPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.address
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.head_count
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Integer headCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.achievement_visable
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Boolean achievementVisable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.add_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.update_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.hired
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Integer hired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.max_pay
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Integer maxPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.district
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.industry_age
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Integer industryAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.skills
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private String skills;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.image
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.start_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.end_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT.desc
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.id
     *
     * @return the value of PROJECT.id
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.id
     *
     * @param id the value for PROJECT.id
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.industry
     *
     * @return the value of PROJECT.industry
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Integer getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.industry
     *
     * @param industry the value for PROJECT.industry
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setIndustry(Integer industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.name
     *
     * @return the value of PROJECT.name
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.name
     *
     * @param name the value for PROJECT.name
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.manager_id
     *
     * @return the value of PROJECT.manager_id
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.manager_id
     *
     * @param managerId the value for PROJECT.manager_id
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.agent_id
     *
     * @return the value of PROJECT.agent_id
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Long getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.agent_id
     *
     * @param agentId the value for PROJECT.agent_id
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.status
     *
     * @return the value of PROJECT.status
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.status
     *
     * @param status the value for PROJECT.status
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.resident
     *
     * @return the value of PROJECT.resident
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Boolean getResident() {
        return resident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.resident
     *
     * @param resident the value for PROJECT.resident
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setResident(Boolean resident) {
        this.resident = resident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.city
     *
     * @return the value of PROJECT.city
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.city
     *
     * @param city the value for PROJECT.city
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.min_pay
     *
     * @return the value of PROJECT.min_pay
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Integer getMinPay() {
        return minPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.min_pay
     *
     * @param minPay the value for PROJECT.min_pay
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setMinPay(Integer minPay) {
        this.minPay = minPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.address
     *
     * @return the value of PROJECT.address
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.address
     *
     * @param address the value for PROJECT.address
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.head_count
     *
     * @return the value of PROJECT.head_count
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Integer getHeadCount() {
        return headCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.head_count
     *
     * @param headCount the value for PROJECT.head_count
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setHeadCount(Integer headCount) {
        this.headCount = headCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.achievement_visable
     *
     * @return the value of PROJECT.achievement_visable
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Boolean getAchievementVisable() {
        return achievementVisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.achievement_visable
     *
     * @param achievementVisable the value for PROJECT.achievement_visable
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setAchievementVisable(Boolean achievementVisable) {
        this.achievementVisable = achievementVisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.add_time
     *
     * @return the value of PROJECT.add_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.add_time
     *
     * @param addTime the value for PROJECT.add_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.update_time
     *
     * @return the value of PROJECT.update_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.update_time
     *
     * @param updateTime the value for PROJECT.update_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.hired
     *
     * @return the value of PROJECT.hired
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Integer getHired() {
        return hired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.hired
     *
     * @param hired the value for PROJECT.hired
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setHired(Integer hired) {
        this.hired = hired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.max_pay
     *
     * @return the value of PROJECT.max_pay
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Integer getMaxPay() {
        return maxPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.max_pay
     *
     * @param maxPay the value for PROJECT.max_pay
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setMaxPay(Integer maxPay) {
        this.maxPay = maxPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.district
     *
     * @return the value of PROJECT.district
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.district
     *
     * @param district the value for PROJECT.district
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.industry_age
     *
     * @return the value of PROJECT.industry_age
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Integer getIndustryAge() {
        return industryAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.industry_age
     *
     * @param industryAge the value for PROJECT.industry_age
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setIndustryAge(Integer industryAge) {
        this.industryAge = industryAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.skills
     *
     * @return the value of PROJECT.skills
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public String getSkills() {
        return skills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.skills
     *
     * @param skills the value for PROJECT.skills
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setSkills(String skills) {
        this.skills = skills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.image
     *
     * @return the value of PROJECT.image
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.image
     *
     * @param image the value for PROJECT.image
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.start_time
     *
     * @return the value of PROJECT.start_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.start_time
     *
     * @param startTime the value for PROJECT.start_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.end_time
     *
     * @return the value of PROJECT.end_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.end_time
     *
     * @param endTime the value for PROJECT.end_time
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT.desc
     *
     * @return the value of PROJECT.desc
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT.desc
     *
     * @param desc the value for PROJECT.desc
     *
     * @mbggenerated Fri Jun 10 16:05:53 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}