package com.iblock.dao.po;

import java.util.Date;

public class ProjectDesigner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_DESIGNER.id
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_DESIGNER.project_id
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_DESIGNER.designer_id
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    private Long designerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_DESIGNER.status
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_DESIGNER.add_time
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_DESIGNER.update_time
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_DESIGNER.id
     *
     * @return the value of PROJECT_DESIGNER.id
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_DESIGNER.id
     *
     * @param id the value for PROJECT_DESIGNER.id
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_DESIGNER.project_id
     *
     * @return the value of PROJECT_DESIGNER.project_id
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_DESIGNER.project_id
     *
     * @param projectId the value for PROJECT_DESIGNER.project_id
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_DESIGNER.designer_id
     *
     * @return the value of PROJECT_DESIGNER.designer_id
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public Long getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_DESIGNER.designer_id
     *
     * @param designerId the value for PROJECT_DESIGNER.designer_id
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public void setDesignerId(Long designerId) {
        this.designerId = designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_DESIGNER.status
     *
     * @return the value of PROJECT_DESIGNER.status
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_DESIGNER.status
     *
     * @param status the value for PROJECT_DESIGNER.status
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_DESIGNER.add_time
     *
     * @return the value of PROJECT_DESIGNER.add_time
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_DESIGNER.add_time
     *
     * @param addTime the value for PROJECT_DESIGNER.add_time
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_DESIGNER.update_time
     *
     * @return the value of PROJECT_DESIGNER.update_time
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_DESIGNER.update_time
     *
     * @param updateTime the value for PROJECT_DESIGNER.update_time
     *
     * @mbggenerated Sun Jun 12 09:38:25 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}