package com.iblock.dao.po;

import java.util.Date;

public class SubProcessExpect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS_EXPECT.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS_EXPECT.process_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS_EXPECT.payment
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Integer payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS_EXPECT.skill_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long skillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS_EXPECT.num
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS_EXPECT.experience
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Integer experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS_EXPECT.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS_EXPECT.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS_EXPECT.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS_EXPECT.id
     *
     * @return the value of SUB_PROCESS_EXPECT.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS_EXPECT.id
     *
     * @param id the value for SUB_PROCESS_EXPECT.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS_EXPECT.process_id
     *
     * @return the value of SUB_PROCESS_EXPECT.process_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS_EXPECT.process_id
     *
     * @param processId the value for SUB_PROCESS_EXPECT.process_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setProcessId(Long processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS_EXPECT.payment
     *
     * @return the value of SUB_PROCESS_EXPECT.payment
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Integer getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS_EXPECT.payment
     *
     * @param payment the value for SUB_PROCESS_EXPECT.payment
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setPayment(Integer payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS_EXPECT.skill_id
     *
     * @return the value of SUB_PROCESS_EXPECT.skill_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS_EXPECT.skill_id
     *
     * @param skillId the value for SUB_PROCESS_EXPECT.skill_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setSkillId(Long skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS_EXPECT.num
     *
     * @return the value of SUB_PROCESS_EXPECT.num
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS_EXPECT.num
     *
     * @param num the value for SUB_PROCESS_EXPECT.num
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS_EXPECT.experience
     *
     * @return the value of SUB_PROCESS_EXPECT.experience
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS_EXPECT.experience
     *
     * @param experience the value for SUB_PROCESS_EXPECT.experience
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS_EXPECT.status
     *
     * @return the value of SUB_PROCESS_EXPECT.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS_EXPECT.status
     *
     * @param status the value for SUB_PROCESS_EXPECT.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS_EXPECT.add_time
     *
     * @return the value of SUB_PROCESS_EXPECT.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS_EXPECT.add_time
     *
     * @param addTime the value for SUB_PROCESS_EXPECT.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS_EXPECT.update_time
     *
     * @return the value of SUB_PROCESS_EXPECT.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS_EXPECT.update_time
     *
     * @param updateTime the value for SUB_PROCESS_EXPECT.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}