package com.iblock.dao.po;

import java.util.Date;

public class SubProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS.project_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS.name
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUB_PROCESS.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS.id
     *
     * @return the value of SUB_PROCESS.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS.id
     *
     * @param id the value for SUB_PROCESS.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS.project_id
     *
     * @return the value of SUB_PROCESS.project_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS.project_id
     *
     * @param projectId the value for SUB_PROCESS.project_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS.name
     *
     * @return the value of SUB_PROCESS.name
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS.name
     *
     * @param name the value for SUB_PROCESS.name
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS.status
     *
     * @return the value of SUB_PROCESS.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS.status
     *
     * @param status the value for SUB_PROCESS.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS.add_time
     *
     * @return the value of SUB_PROCESS.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS.add_time
     *
     * @param addTime the value for SUB_PROCESS.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUB_PROCESS.update_time
     *
     * @return the value of SUB_PROCESS.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUB_PROCESS.update_time
     *
     * @param updateTime the value for SUB_PROCESS.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}