package com.iblock.dao.po;

import java.util.Date;

public class UserGeo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.user_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.province
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.province_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.city
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.city_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.district
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.district_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Integer districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.address
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.latitude
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.longitude
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.status
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.add_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_GEO.update_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.id
     *
     * @return the value of USER_GEO.id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.id
     *
     * @param id the value for USER_GEO.id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.user_id
     *
     * @return the value of USER_GEO.user_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.user_id
     *
     * @param userId the value for USER_GEO.user_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.province
     *
     * @return the value of USER_GEO.province
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.province
     *
     * @param province the value for USER_GEO.province
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.province_id
     *
     * @return the value of USER_GEO.province_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.province_id
     *
     * @param provinceId the value for USER_GEO.province_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.city
     *
     * @return the value of USER_GEO.city
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.city
     *
     * @param city the value for USER_GEO.city
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.city_id
     *
     * @return the value of USER_GEO.city_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.city_id
     *
     * @param cityId the value for USER_GEO.city_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.district
     *
     * @return the value of USER_GEO.district
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.district
     *
     * @param district the value for USER_GEO.district
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.district_id
     *
     * @return the value of USER_GEO.district_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.district_id
     *
     * @param districtId the value for USER_GEO.district_id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.address
     *
     * @return the value of USER_GEO.address
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.address
     *
     * @param address the value for USER_GEO.address
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.latitude
     *
     * @return the value of USER_GEO.latitude
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.latitude
     *
     * @param latitude the value for USER_GEO.latitude
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.longitude
     *
     * @return the value of USER_GEO.longitude
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.longitude
     *
     * @param longitude the value for USER_GEO.longitude
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.status
     *
     * @return the value of USER_GEO.status
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.status
     *
     * @param status the value for USER_GEO.status
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.add_time
     *
     * @return the value of USER_GEO.add_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.add_time
     *
     * @param addTime the value for USER_GEO.add_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_GEO.update_time
     *
     * @return the value of USER_GEO.update_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_GEO.update_time
     *
     * @param updateTime the value for USER_GEO.update_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}