package com.iblock.dao.po;

import java.util.Date;

public class UserRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RELATION.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RELATION.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RELATION.friend_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RELATION.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RELATION.desc
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RELATION.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RELATION.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RELATION.id
     *
     * @return the value of USER_RELATION.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RELATION.id
     *
     * @param id the value for USER_RELATION.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RELATION.user_id
     *
     * @return the value of USER_RELATION.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RELATION.user_id
     *
     * @param userId the value for USER_RELATION.user_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RELATION.friend_id
     *
     * @return the value of USER_RELATION.friend_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RELATION.friend_id
     *
     * @param friendId the value for USER_RELATION.friend_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RELATION.status
     *
     * @return the value of USER_RELATION.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RELATION.status
     *
     * @param status the value for USER_RELATION.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RELATION.desc
     *
     * @return the value of USER_RELATION.desc
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RELATION.desc
     *
     * @param desc the value for USER_RELATION.desc
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RELATION.add_time
     *
     * @return the value of USER_RELATION.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RELATION.add_time
     *
     * @param addTime the value for USER_RELATION.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RELATION.update_time
     *
     * @return the value of USER_RELATION.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RELATION.update_time
     *
     * @param updateTime the value for USER_RELATION.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}