package com.iblock.dao.po;

import java.util.Date;

public class UserRating {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RATING.id
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RATING.user_id
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RATING.operator
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    private Long operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RATING.rating
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    private Integer rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RATING.status
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RATING.update_time
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RATING.add_time
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RATING.id
     *
     * @return the value of USER_RATING.id
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RATING.id
     *
     * @param id the value for USER_RATING.id
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RATING.user_id
     *
     * @return the value of USER_RATING.user_id
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RATING.user_id
     *
     * @param userId the value for USER_RATING.user_id
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RATING.operator
     *
     * @return the value of USER_RATING.operator
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RATING.operator
     *
     * @param operator the value for USER_RATING.operator
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RATING.rating
     *
     * @return the value of USER_RATING.rating
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RATING.rating
     *
     * @param rating the value for USER_RATING.rating
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RATING.status
     *
     * @return the value of USER_RATING.status
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RATING.status
     *
     * @param status the value for USER_RATING.status
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RATING.update_time
     *
     * @return the value of USER_RATING.update_time
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RATING.update_time
     *
     * @param updateTime the value for USER_RATING.update_time
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RATING.add_time
     *
     * @return the value of USER_RATING.add_time
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RATING.add_time
     *
     * @param addTime the value for USER_RATING.add_time
     *
     * @mbggenerated Tue Jul 19 21:54:06 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}