package com.iblock.dao.po;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.user_name
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.password
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.role
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Byte role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.mobile
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.sex
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.status
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.head_figure
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private String headFigure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.add_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.update_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.id
     *
     * @return the value of USER.id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.id
     *
     * @param id the value for USER.id
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.user_name
     *
     * @return the value of USER.user_name
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.user_name
     *
     * @param userName the value for USER.user_name
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.password
     *
     * @return the value of USER.password
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.password
     *
     * @param password the value for USER.password
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.role
     *
     * @return the value of USER.role
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Byte getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.role
     *
     * @param role the value for USER.role
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setRole(Byte role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.mobile
     *
     * @return the value of USER.mobile
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.mobile
     *
     * @param mobile the value for USER.mobile
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.sex
     *
     * @return the value of USER.sex
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.sex
     *
     * @param sex the value for USER.sex
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.status
     *
     * @return the value of USER.status
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.status
     *
     * @param status the value for USER.status
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.head_figure
     *
     * @return the value of USER.head_figure
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public String getHeadFigure() {
        return headFigure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.head_figure
     *
     * @param headFigure the value for USER.head_figure
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setHeadFigure(String headFigure) {
        this.headFigure = headFigure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.add_time
     *
     * @return the value of USER.add_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.add_time
     *
     * @param addTime the value for USER.add_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.update_time
     *
     * @return the value of USER.update_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.update_time
     *
     * @param updateTime the value for USER.update_time
     *
     * @mbggenerated Thu Feb 04 15:04:32 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}