package com.iblock.dao.po;

import java.util.Date;

public class WorkExperience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EXPERIENCE.id
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EXPERIENCE.user_id
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EXPERIENCE.industry
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    private Integer industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EXPERIENCE.corporate
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    private String corporate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EXPERIENCE.year
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EXPERIENCE.status
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EXPERIENCE.add_time
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EXPERIENCE.update_time
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EXPERIENCE.desc
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EXPERIENCE.id
     *
     * @return the value of WORK_EXPERIENCE.id
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EXPERIENCE.id
     *
     * @param id the value for WORK_EXPERIENCE.id
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EXPERIENCE.user_id
     *
     * @return the value of WORK_EXPERIENCE.user_id
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EXPERIENCE.user_id
     *
     * @param userId the value for WORK_EXPERIENCE.user_id
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EXPERIENCE.industry
     *
     * @return the value of WORK_EXPERIENCE.industry
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public Integer getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EXPERIENCE.industry
     *
     * @param industry the value for WORK_EXPERIENCE.industry
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public void setIndustry(Integer industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EXPERIENCE.corporate
     *
     * @return the value of WORK_EXPERIENCE.corporate
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public String getCorporate() {
        return corporate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EXPERIENCE.corporate
     *
     * @param corporate the value for WORK_EXPERIENCE.corporate
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public void setCorporate(String corporate) {
        this.corporate = corporate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EXPERIENCE.year
     *
     * @return the value of WORK_EXPERIENCE.year
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EXPERIENCE.year
     *
     * @param year the value for WORK_EXPERIENCE.year
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EXPERIENCE.status
     *
     * @return the value of WORK_EXPERIENCE.status
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EXPERIENCE.status
     *
     * @param status the value for WORK_EXPERIENCE.status
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EXPERIENCE.add_time
     *
     * @return the value of WORK_EXPERIENCE.add_time
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EXPERIENCE.add_time
     *
     * @param addTime the value for WORK_EXPERIENCE.add_time
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EXPERIENCE.update_time
     *
     * @return the value of WORK_EXPERIENCE.update_time
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EXPERIENCE.update_time
     *
     * @param updateTime the value for WORK_EXPERIENCE.update_time
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EXPERIENCE.desc
     *
     * @return the value of WORK_EXPERIENCE.desc
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EXPERIENCE.desc
     *
     * @param desc the value for WORK_EXPERIENCE.desc
     *
     * @mbggenerated Sun Feb 14 20:06:43 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}