package com.iblock.dao.po;

import java.util.Date;

public class WorkflowLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKFLOW_LOG.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKFLOW_LOG.workflow_type
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Byte workflowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKFLOW_LOG.out_biz_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Long outBizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKFLOW_LOG.workflow_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private String workflowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKFLOW_LOG.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKFLOW_LOG.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKFLOW_LOG.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKFLOW_LOG.id
     *
     * @return the value of WORKFLOW_LOG.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKFLOW_LOG.id
     *
     * @param id the value for WORKFLOW_LOG.id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKFLOW_LOG.workflow_type
     *
     * @return the value of WORKFLOW_LOG.workflow_type
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Byte getWorkflowType() {
        return workflowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKFLOW_LOG.workflow_type
     *
     * @param workflowType the value for WORKFLOW_LOG.workflow_type
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setWorkflowType(Byte workflowType) {
        this.workflowType = workflowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKFLOW_LOG.out_biz_id
     *
     * @return the value of WORKFLOW_LOG.out_biz_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Long getOutBizId() {
        return outBizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKFLOW_LOG.out_biz_id
     *
     * @param outBizId the value for WORKFLOW_LOG.out_biz_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setOutBizId(Long outBizId) {
        this.outBizId = outBizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKFLOW_LOG.workflow_id
     *
     * @return the value of WORKFLOW_LOG.workflow_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public String getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKFLOW_LOG.workflow_id
     *
     * @param workflowId the value for WORKFLOW_LOG.workflow_id
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setWorkflowId(String workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKFLOW_LOG.status
     *
     * @return the value of WORKFLOW_LOG.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKFLOW_LOG.status
     *
     * @param status the value for WORKFLOW_LOG.status
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKFLOW_LOG.add_time
     *
     * @return the value of WORKFLOW_LOG.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKFLOW_LOG.add_time
     *
     * @param addTime the value for WORKFLOW_LOG.add_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKFLOW_LOG.update_time
     *
     * @return the value of WORKFLOW_LOG.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKFLOW_LOG.update_time
     *
     * @param updateTime the value for WORKFLOW_LOG.update_time
     *
     * @mbggenerated Mon Feb 01 11:51:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}